/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "HttpPostEndpointImpl.hpp"
#include "HttpPostEndpointImplFactory.hpp"
#include "HttpPostEndpointInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *HttpPostEndpointImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  HttpPostEndpointConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline(), constructor.getDisconnectionTimeout(), constructor.getUseEncodedMedia() );
}

void
HttpPostEndpointImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  HttpEndpointImpl::invoke (obj, methodName, params, response);
}

bool
HttpPostEndpointImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  if ("EndOfStream" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalEndOfStream.connect ([ &, wh] (EndOfStream event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "EndOfStream";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  return HttpEndpointImpl::connect (eventType, handler);
}

void
HttpPostEndpointImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'HttpPostEndpointImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::HttpPostEndpointImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::HttpPostEndpointImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::HttpPostEndpointImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::HttpPostEndpoint> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::HttpPostEndpointImpl> aux = std::dynamic_pointer_cast<kurento::HttpPostEndpointImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::HttpPostEndpoint> (aux);
}

} /* kurento */