/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "IceCandidate.hpp"
#include "IceCandidatePair.hpp"
#include "WebRtcEndpointImpl.hpp"
#include "WebRtcEndpointImplFactory.hpp"
#include "WebRtcEndpointInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

MediaObjectImpl *WebRtcEndpointImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  WebRtcEndpointConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline(), constructor.getUseDataChannels() );
}

void
WebRtcEndpointImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "gatherCandidates") {
    kurento::JsonSerializer s (false);
    WebRtcEndpointMethodGatherCandidates method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<WebRtcEndpoint> (obj) );
    return;
  }

  if (methodName == "addIceCandidate") {
    kurento::JsonSerializer s (false);
    WebRtcEndpointMethodAddIceCandidate method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<WebRtcEndpoint> (obj) );
    return;
  }

  if (methodName == "createDataChannel") {
    kurento::JsonSerializer s (false);
    WebRtcEndpointMethodCreateDataChannel method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<WebRtcEndpoint> (obj) );
    return;
  }

  if (methodName == "closeDataChannel") {
    kurento::JsonSerializer s (false);
    WebRtcEndpointMethodCloseDataChannel method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<WebRtcEndpoint> (obj) );
    return;
  }

  if (methodName == "getStunServerAddress") {
    std::string ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->getStunServerAddress ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "setStunServerAddress") {
    kurento::JsonSerializer s (false);
    std::string stunServerAddress;
    s.JsonValue = params;

    if (!s.JsonValue.isMember ("stunServerAddress") || !s.JsonValue["stunServerAddress"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'stunServerAddress' parameter should be a string");
    }

    if (!s.IsWriter) {
      s.SerializeNVP (stunServerAddress);
      std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->setStunServerAddress (stunServerAddress);
    }
    return;
  }

  if (methodName == "getStunServerPort") {
    int ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->getStunServerPort ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "setStunServerPort") {
    kurento::JsonSerializer s (false);
    int stunServerPort;
    s.JsonValue = params;

    if (!s.JsonValue.isMember ("stunServerPort") || !s.JsonValue["stunServerPort"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'stunServerPort' parameter should be a integer");
    }

    if (!s.IsWriter) {
      s.SerializeNVP (stunServerPort);
      std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->setStunServerPort (stunServerPort);
    }
    return;
  }

  if (methodName == "getTurnUrl") {
    std::string ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->getTurnUrl ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  if (methodName == "setTurnUrl") {
    kurento::JsonSerializer s (false);
    std::string turnUrl;
    s.JsonValue = params;

    if (!s.JsonValue.isMember ("turnUrl") || !s.JsonValue["turnUrl"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'turnUrl' parameter should be a string");
    }

    if (!s.IsWriter) {
      s.SerializeNVP (turnUrl);
      std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->setTurnUrl (turnUrl);
    }
    return;
  }

  if (methodName == "getICECandidatePairs") {
    std::vector<std::shared_ptr<IceCandidatePair>> ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<WebRtcEndpoint> (obj)->getICECandidatePairs ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  BaseRtpEndpointImpl::invoke (obj, methodName, params, response);
}

bool
WebRtcEndpointImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  if ("OnIceCandidate" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnIceCandidate.connect ([ &, wh] (OnIceCandidate event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "OnIceCandidate";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  if ("OnIceGatheringDone" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnIceGatheringDone.connect ([ &, wh] (OnIceGatheringDone event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "OnIceGatheringDone";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  if ("OnIceComponentStateChanged" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnIceComponentStateChanged.connect ([ &, wh] (OnIceComponentStateChanged event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "OnIceComponentStateChanged";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  if ("OnDataChannelOpened" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnDataChannelOpened.connect ([ &, wh] (OnDataChannelOpened event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "OnDataChannelOpened";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  if ("OnDataChannelClosed" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalOnDataChannelClosed.connect ([ &, wh] (OnDataChannelClosed event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "OnDataChannelClosed";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  if ("NewCandidatePairSelected" == eventType) {
    std::weak_ptr<EventHandler> wh = handler;

    sigc::connection conn = signalNewCandidatePairSelected.connect ([ &, wh] (NewCandidatePairSelected event) {
      JsonSerializer s (true);

      s.Serialize ("data", event);
      s.Serialize ("object", this);
      s.JsonValue["type"] = "NewCandidatePairSelected";

      std::shared_ptr<EventHandler> lh = wh.lock();

      if (lh) {
        lh->sendEvent (s.JsonValue);
      }
    });
    handler->setConnection (conn);
    return true;
  }

  return BaseRtpEndpointImpl::connect (eventType, handler);
}

void
WebRtcEndpointImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'WebRtcEndpointImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::WebRtcEndpointImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::WebRtcEndpointImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::WebRtcEndpointImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::WebRtcEndpoint> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::WebRtcEndpointImpl> aux = std::dynamic_pointer_cast<kurento::WebRtcEndpointImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::WebRtcEndpoint> (aux);
}

} /* kurento */