/* Autogenerated with kurento-module-creator */

#include "OnIceGatheringDone.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <time.h>
#include <string>

namespace kurento
{

void
OnIceGatheringDone::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

}

} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::OnIceGatheringDone> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::OnIceGatheringDone() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */